[server]
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#9595ec"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#030404"
font = "sans serif"